[project]
name = "markdown-table-generator"
version = "0.1.0"

authors = [
    { name="Thomas Screven", email="tscreven@gmail.com"}
]
description = "Generate Markdown formatted tables from data files."
readme = "README.md"

dependencies = [
    "pandas", 
    "numpy", 
    "openpyxl"
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "Apache-2.0"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/tscreven/MarkdownTableGenerator"
Issues = "https://github.com/tscreven/MarkdownTableGenerator/issues"

[project.scripts]
markdown-table = "main:main"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["main", "table_generator"]
